### ISSUE TITLE
Telegram [RUS]

### ISSUE THREAD

**Issue by JumperAlexey** [idlesign/torrt#10]
Доброго времени суток. 
Описываю порядок действий и свой вопрос. Спасибо. 
0 - система lubuntu - все стоит на 1 компе
1 - поставил питон 2.7
2 - поставил torrt
3 - настроил transmission rpc и nnm-club и telegram согластно инстурции
4 - проверил путем добавления ссылки на скачку через консоль
torrt add_torrent http://nnm-club.name...
результат: ссылка добавилась, торрент скачался и началась загрузка файла. файл удачно скачался.
Но при этом в чат телеграма ничего не пришло.
Вопросы:
1 Должно ли быть уведомление при первичной загрузке торрент файла?
2 Как можно запустить принудительно из консоли тестовое сообщение в телеграм? 
Для проверки работы телеграма я сделал ссылку в формате и через браузер на той же машине отрыл ее.
Результат - сообщение пришло в чат.
Ссылка:
https://api.telegram.org/botTOKEN/sendMessage?chat_id=CHAT_ID&text=Hi

**Comment by idlesign** [comment]
Приветствую.

1. Нет, при регистрации раздачи оповещение не приходит. Оповещение вызывает только команда `walk`.

2. Нет, в консольный интерфейс команда проверки не вынесена. Можно, однако, выполнять консольные команды с ключём `--verbose`, при этом будет выводится информация о том, была ли произведена рассылка.

**Comment by JumperAlexey** [comment]
1 - после добавления торрента в список я делал команду walk, но уведомления не было. однако и сама раздача не обновлялась. правильно понимаю - уведомление будет ТОЛЬКО после автоматического автовления торрента?
2 - команду вот в таком виде надо делать? 
torrt configure_notifier telegram --verbose
при таком запуске получаю следующий результат:
DEBUG: Bootstrapping torrt environment ...
DEBUG: Importing RPC classes ...
DEBUG: Registering `deluge` from <class 'torrt.rpc.deluge.DelugeRPC'> ...
DEBUG: Registering `transmission` from <class 'torrt.rpc.transmission.TransmissionRPC'> ...
DEBUG: Registering `utorrent` from <class 'torrt.rpc.utorrent.UTorrentRPC'> ...
DEBUG: Importing Tracker classes ...
DEBUG: Registering `tr.anidub.com` from <class 'torrt.trackers.anidub.AniDUBTracker'> ...
DEBUG: Registering `nnm-club.me` from <class 'torrt.trackers.nnmclub.NNMClubTracker'> ...
DEBUG: Registering `rutor.org` from <class 'torrt.trackers.rutor.RutorTracker'> ...
DEBUG: Registering `rutracker.org` from <class 'torrt.trackers.rutracker.RuTrackerTracker'> ...
DEBUG: Importing Notifier classes ...
DEBUG: Registering `email` from <class 'torrt.notifiers.mail.EmailNotifier'> ...
DEBUG: Registering `telegram` from <class 'torrt.notifiers.telegram.TelegramNotifier'> ...
DEBUG: Initializing objects registries from configuration file ...
DEBUG: Loading configuration file /root/.torrt/config.json ...
DEBUG: Spawning `TelegramNotifier` object with the given settings ...
DEBUG: Registering `telegram` from <torrt.notifiers.telegram.TelegramNotifier object at 0xb64df70c> ...
DEBUG: Spawning `TransmissionRPC` object with the given settings ...
DEBUG: Registering `transmission` from <torrt.rpc.transmission.TransmissionRPC object at 0xb64df74c> ...
DEBUG: Spawning `NNMClubTracker` object with the given settings ...
DEBUG: Registering `nnm-club.me` from <torrt.trackers.nnmclub.NNMClubTracker object at 0xb64df76c> ...
INFO: Configuring `telegram` notifier ...
DEBUG: Spawning `TelegramNotifier` object with the given settings ...
Traceback (most recent call last):
  File "/usr/local/bin/torrt", line 11, in <module>
    sys.exit(process_commands())
  File "/usr/local/lib/python2.7/dist-packages/torrt/main.py", line 196, in process_commands
    configure_notifier(args['notifier_alias'], settings_dict_from_list(args['settings']))
  File "/usr/local/lib/python2.7/dist-packages/torrt/toolbox.py", line 88, in configure_notifier
    notifier = notification_class.spawn_with_settings(settings_dict)
  File "/usr/local/lib/python2.7/dist-packages/torrt/utils.py", line 235, in spawn_with_settings
    return cls(**settings)
TypeError: __init__() takes exactly 3 arguments (1 given)

**Comment by idlesign** [comment]
1. Да, правильно.
2. При настройке оповещателя нужно указать два параметра: `token` и `chat_id`. А с ключём `--verbose` имеет смысл запускать команды `walk`, чтобы более детально видеть, что происходит.

**Comment by JumperAlexey** [comment]
1 - будет ли доработка, которая позволит получать сообщение при первичной загрузке торрента?
2 - token chat_id я прописал. проверил в конфиг файле - все ок.
выполнил команду walk с ключём --verbose - ниже результат:
DEBUG: Bootstrapping torrt environment ...
DEBUG: Importing RPC classes ...
DEBUG: Registering `deluge` from <class 'torrt.rpc.deluge.DelugeRPC'> ...
DEBUG: Registering `transmission` from <class 'torrt.rpc.transmission.TransmissionRPC'> ...
DEBUG: Registering `utorrent` from <class 'torrt.rpc.utorrent.UTorrentRPC'> ...
DEBUG: Importing Tracker classes ...
DEBUG: Registering `tr.anidub.com` from <class 'torrt.trackers.anidub.AniDUBTracker'> ...
DEBUG: Registering `nnm-club.me` from <class 'torrt.trackers.nnmclub.NNMClubTracker'> ...
DEBUG: Registering `rutor.org` from <class 'torrt.trackers.rutor.RutorTracker'> ...
DEBUG: Registering `rutracker.org` from <class 'torrt.trackers.rutracker.RuTrackerTracker'> ...
DEBUG: Importing Notifier classes ...
DEBUG: Registering `email` from <class 'torrt.notifiers.mail.EmailNotifier'> ...
DEBUG: Registering `telegram` from <class 'torrt.notifiers.telegram.TelegramNotifier'> ...
DEBUG: Initializing objects registries from configuration file ...
DEBUG: Loading configuration file /root/.torrt/config.json ...
DEBUG: Spawning `TelegramNotifier` object with the given settings ...
DEBUG: Registering `telegram` from <torrt.notifiers.telegram.TelegramNotifier object at 0xb64d06ac> ...
DEBUG: Spawning `TransmissionRPC` object with the given settings ...
DEBUG: Registering `transmission` from <torrt.rpc.transmission.TransmissionRPC object at 0xb64d06ec> ...
DEBUG: Spawning `NNMClubTracker` object with the given settings ...
DEBUG: Registering `nnm-club.me` from <torrt.trackers.nnmclub.NNMClubTracker object at 0xb64d070c> ...
INFO: Torrent walk is triggered
DEBUG: Loading configuration file /root/.torrt/config.json ...
INFO: Torrent walk is started
INFO: Getting torrents from `transmission` ...
DEBUG: RPC method `torrent-get` ...
DEBUG: Starting new HTTP connection (1): 127.0.0.1
ERROR: Failed to query RPC `http://127.0.0.1:9091/transmission/rpc`: HTTPConnectionPool(host='127.0.0.1', port=9091): Max retries exceeded with url: /transmission/rpc (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0xb64de7cc>: Failed to establish a new connection: [Errno 111] Connection refused',))
ERROR: Walk failed. Reason: HTTPConnectionPool(host='127.0.0.1', port=9091): Max retries exceeded with url: /transmission/rpc (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0xb64de7cc>: Failed to establish a new connection: [Errno 111] Connection refused',))
DEBUG: Loading configuration file /root/.torrt/config.json ...
DEBUG: Saving configuration file /root/.torrt/config.json ...
INFO: Torrent walk is finished

**Comment by JumperAlexey** [comment]
я так понял что не стартанул сам transmissin - после его запуска повторно выполнил команду и вот что получил.

DEBUG: Bootstrapping torrt environment ...
DEBUG: Importing RPC classes ...
DEBUG: Registering `deluge` from <class 'torrt.rpc.deluge.DelugeRPC'> ...
DEBUG: Registering `transmission` from <class 'torrt.rpc.transmission.TransmissionRPC'> ...
DEBUG: Registering `utorrent` from <class 'torrt.rpc.utorrent.UTorrentRPC'> ...
DEBUG: Importing Tracker classes ...
DEBUG: Registering `tr.anidub.com` from <class 'torrt.trackers.anidub.AniDUBTracker'> ...
DEBUG: Registering `nnm-club.me` from <class 'torrt.trackers.nnmclub.NNMClubTracker'> ...
DEBUG: Registering `rutor.org` from <class 'torrt.trackers.rutor.RutorTracker'> ...
DEBUG: Registering `rutracker.org` from <class 'torrt.trackers.rutracker.RuTrackerTracker'> ...
DEBUG: Importing Notifier classes ...
DEBUG: Registering `email` from <class 'torrt.notifiers.mail.EmailNotifier'> ...
DEBUG: Registering `telegram` from <class 'torrt.notifiers.telegram.TelegramNotifier'> ...
DEBUG: Initializing objects registries from configuration file ...
DEBUG: Loading configuration file /root/.torrt/config.json ...
DEBUG: Spawning `TelegramNotifier` object with the given settings ...
DEBUG: Registering `telegram` from <torrt.notifiers.telegram.TelegramNotifier object at 0xb64936ac> ...
DEBUG: Spawning `TransmissionRPC` object with the given settings ...
DEBUG: Registering `transmission` from <torrt.rpc.transmission.TransmissionRPC object at 0xb64936ec> ...
DEBUG: Spawning `NNMClubTracker` object with the given settings ...
DEBUG: Registering `nnm-club.me` from <torrt.trackers.nnmclub.NNMClubTracker object at 0xb649370c> ...
INFO: Torrent walk is triggered
DEBUG: Loading configuration file /root/.torrt/config.json ...
INFO: Torrent walk postponed till 2017-09-26 13:29:05 (now 2017-09-26 13:16:38)

**Comment by idlesign** [comment]
1. Я про такую доработку не думал. Не уверен, что она к месту: сейчас в оповещении говорится об обновлении, а не о добавлении.

2. Torrent walk postponed till 2017-09-26 13:29:05 (now 2017-09-26 13:16:38)
`walk` не даст вызывать себя слишком часто. Чтобы принудить его есть флаг `-f` (от force).

**Comment by JumperAlexey** [comment]
Просто было бы интересно развить тему дальше и сделать полноценного бота. ) ну это так. Мысли в слух. Оставлю пока чтотнастройки в таком виде и гляну что будет после обновления торрента. А пока что пойду курить питон, что бы исходники почитать. Спасибо )

**Comment by idlesign** [comment]
Пожалуйста.
Обращение закрываю.
