### ISSUE TITLE
Cannot enable it in Deluge

### ISSUE THREAD

**Issue by perfect7gentleman** [idlesign/torrt#18]
I got deluge-server running on separate machine. Dependencies are installed, torrentool works.
I can't enable it in Deluge-gtk running on client machine.
Do i need to install dependencies required by torrt on client?

**Comment by idlesign** [comment]
That's probably unrelated to ``torrt``. Be sure you've installed latest version of https://github.com/idlesign/deluge-webapi  using installation instructions. Please use ``deluge-webapi`` project page to file related issues if any.

``torrt`` requirements apply to the system you want to run ``torrt`` on.

**Comment by perfect7gentleman** [comment]
so torrt is not deluge plugin, right?

**Comment by idlesign** [comment]
Right you are. Torrt is for torrent updates, it can use Deluge or other torrent client for that. To use it with  Deluge you should install ``deluge-webapi``. 

In the beginning there was https://github.com/idlesign/deluge-updatorr (which is indeed a plugin for Deluge) but now it's depricated.

**Comment by perfect7gentleman** [comment]
Продолжим по-русски, однако.
Ещё один момент:
на сервере Deluge собран без поддержки WebInterface. 
```
[ebuild   R   *] net-p2p/deluge-1.3.9999::pg_overlay  USE="-console -geoip -gtk -libnotify -sound -webinterface"
```
Он обязателен?
