### ISSUE TITLE
nnm-club. Consecutive login attempt detected.. [rus]

### ISSUE THREAD

**Issue by qMBQx8GH** [idlesign/torrt#2]
При проверке обновлений торрентов начал получать ошибку "Consecutive login attempt detected...".
При этом проверка других трекеров завершается вместе с завершением программы.
Не уверен, что исправление правильное, но работает:
```
diff --git a/torrt/base_tracker.py b/torrt/base_tracker.py
index 6a9a2c8..33d0424 100644
--- a/torrt/base_tracker.py
+++ b/torrt/base_tracker.py
@@ -259,7 +259,8 @@ class GenericPrivateTracker(GenericPublicTracker):
         LOGGER.debug('Trying to login at %s ...', self.login_url)
 
         if self.logged_in:
-            raise TorrtTrackerException('Consecutive login attempt detected at `%s`' % self.__class__.__name__)
+            return True
 
         if not self.username or self.password is None:
             return False
```

**Comment by idlesign** [comment]
Исключение с текстом "Consecutive login attempt detected..." говорит о том, что что-то нарушилось в ходе авторизации и мы пытаемся авторизоваться снова. Если принять ваше решение (а оно действительно рабочее), то у нас будет шанс попасть в бесконечный цикл авторизации. 

А неплохо было бы рассмотреть, что приводит к попыткам повторной авторизации. Возможно что-то поменяли на самом nnm.

Спасибо за сообщение. Погляжу, как будет время.

**Comment by dmzkrsk** [comment]
Заметил, что такое возникает на "закрытых" в России темах. 
Тема раздачи есть, но внутри ссылки на торрент нет

**Comment by idlesign** [comment]
Спасибо за наблюдение.
Если только на закрытых, то смысла что-то менять нет: всё равно мы никак до файла не достучимся.

**Comment by idlesign** [comment]
Закрываю запрос: считаем, что ошибка проявляется в закрытых (для страны) темах, из которых мы в любом случае не сможем получить ссылку на обновлённый торрент.

Участникам спасибо.
