### ISSUE TITLE
can't add rutracker torrents - download link not found

### ISSUE THREAD

**Issue by Bart39** [idlesign/torrt#20]
using the example from the quickstart guide i am unable to add a torrent from rutracker

```
torrt add_torrent http://rutracker.org/forum/viewtopic.php?t=4430338 --verbose
DEBUG: Bootstrapping torrt environment ...
DEBUG: Importing RPC classes ...
DEBUG: Registering `deluge` from <class 'torrt.rpc.deluge.DelugeRPC'> ...
DEBUG: Registering `qbittorrent` from <class 'torrt.rpc.qbittorrent.QBittorrentRPC'> ...
DEBUG: Registering `transmission` from <class 'torrt.rpc.transmission.TransmissionRPC'> ...
DEBUG: Registering `utorrent` from <class 'torrt.rpc.utorrent.UTorrentRPC'> ...
DEBUG: Importing Tracker classes ...
DEBUG: Registering `tr.anidub.com` from <class 'torrt.trackers.anidub.AniDUBTracker'> ...
DEBUG: Registering `kinozal.tv` from <class 'torrt.trackers.kinozal.KinozalTracker'> ...
DEBUG: Registering `nnm-club.me` from <class 'torrt.trackers.nnmclub.NNMClubTracker'> ...
DEBUG: Registering `rutor.org` from <class 'torrt.trackers.rutor.RutorTracker'> ...
DEBUG: Registering `rutracker.org` from <class 'torrt.trackers.rutracker.RuTrackerTracker'> ...
DEBUG: Importing Notifier classes ...
DEBUG: Registering `email` from <class 'torrt.notifiers.mail.EmailNotifier'> ...
DEBUG: Registering `telegram` from <class 'torrt.notifiers.telegram.TelegramNotifier'> ...
DEBUG: Initializing objects registries from configuration file ...
DEBUG: Loading configuration file /home/mark/.torrt/config.json ...
DEBUG: Spawning `DelugeRPC` object with the given settings ...
DEBUG: Registering `deluge` from <torrt.rpc.deluge.DelugeRPC object at 0x7f42775469d0> ...
DEBUG: Spawning `RuTrackerTracker` object with the given settings ...
DEBUG: Registering `rutracker.org` from <torrt.trackers.rutracker.RuTrackerTracker object at 0x7f4277546a10> ...
DEBUG: Adding torrent from `http://rutracker.org/forum/viewtopic.php?t=4430338` ...
DEBUG: Downloading torrent file from `http://rutracker.org/forum/viewtopic.php?t=4430338` ...
DEBUG: Picking a mirror ...
DEBUG: Probing mirror: `http://rutracker.org` ...
DEBUG: Starting new HTTP connection (1): rutracker.org
DEBUG: http://rutracker.org:80 "GET / HTTP/1.1" 301 178
DEBUG: http://rutracker.org:80 "GET /forum/index.php HTTP/1.1" 200 None
DEBUG: Fetching http://rutracker.org/forum/viewtopic.php?t=4430338 ...
DEBUG: Starting new HTTP connection (1): rutracker.org
DEBUG: http://rutracker.org:80 "GET /forum/viewtopic.php?t=4430338 HTTP/1.1" 302 154
DEBUG: Starting new HTTPS connection (1): rutracker.org
DEBUG: https://rutracker.org:443 "GET /forum/viewtopic.php?t=4430338 HTTP/1.1" 200 None
ERROR: Cannot find torrent file download link at http://rutracker.org/forum/viewtopic.php?t=4430338
WARNING: Unable to get torrent from `http://rutracker.org/forum/viewtopic.php?t=4430338`
ERROR: Unable to add torrent from `http://rutracker.org/forum/viewtopic.php?t=4430338`
```

**Comment by idlesign** [comment]
Seems like you're unauthorized, so there's no .torrent donwload link on that page.

**Comment by Bart39** [comment]
```
torrt configure_tracker rutracker.org username=XXXXX password=XXXXX --verbose
DEBUG: Bootstrapping torrt environment ...
DEBUG: Importing RPC classes ...
DEBUG: Registering `deluge` from <class 'torrt.rpc.deluge.DelugeRPC'> ...
DEBUG: Registering `qbittorrent` from <class 'torrt.rpc.qbittorrent.QBittorrentRPC'> ...
DEBUG: Registering `transmission` from <class 'torrt.rpc.transmission.TransmissionRPC'> ...
DEBUG: Registering `utorrent` from <class 'torrt.rpc.utorrent.UTorrentRPC'> ...
DEBUG: Importing Tracker classes ...
DEBUG: Registering `tr.anidub.com` from <class 'torrt.trackers.anidub.AniDUBTracker'> ...
DEBUG: Registering `kinozal.tv` from <class 'torrt.trackers.kinozal.KinozalTracker'> ...
DEBUG: Registering `nnm-club.me` from <class 'torrt.trackers.nnmclub.NNMClubTracker'> ...
DEBUG: Registering `rutor.org` from <class 'torrt.trackers.rutor.RutorTracker'> ...
DEBUG: Registering `rutracker.org` from <class 'torrt.trackers.rutracker.RuTrackerTracker'> ...
DEBUG: Importing Notifier classes ...
DEBUG: Registering `email` from <class 'torrt.notifiers.mail.EmailNotifier'> ...
DEBUG: Registering `telegram` from <class 'torrt.notifiers.telegram.TelegramNotifier'> ...
DEBUG: Initializing objects registries from configuration file ...
DEBUG: Loading configuration file /home/mark/.torrt/config.json ...
DEBUG: Spawning `DelugeRPC` object with the given settings ...
DEBUG: Registering `deluge` from <torrt.rpc.deluge.DelugeRPC object at 0x7ffa73ce0a10> ...
DEBUG: Spawning `RuTrackerTracker` object with the given settings ...
DEBUG: Registering `rutracker.org` from <torrt.trackers.rutracker.RuTrackerTracker object at 0x7ffa73ce0a50> ...
INFO: Configuring `rutracker.org` tracker ...
DEBUG: Spawning `RuTrackerTracker` object with the given settings ...
DEBUG: Trying to login at https://rutracker.org/forum/login.php ...
DEBUG: Picking a mirror ...
DEBUG: Probing mirror: `https://rutracker.org` ...
DEBUG: Starting new HTTPS connection (1): rutracker.org
DEBUG: https://rutracker.org:443 "GET / HTTP/1.1" 301 178
DEBUG: https://rutracker.org:443 "GET /forum/index.php HTTP/1.1" 200 None
DEBUG: Fetching https://rutracker.org/forum/login.php ...
DEBUG: Starting new HTTPS connection (1): rutracker.org
DEBUG: https://rutracker.org:443 "POST /forum/login.php HTTP/1.1" 302 None
DEBUG: Loading configuration file /home/mark/.torrt/config.json ...
DEBUG: Saving configuration file /home/mark/.torrt/config.json ...
DEBUG: Login is successful
DEBUG: Loading configuration file /home/mark/.torrt/config.json ...
DEBUG: Saving configuration file /home/mark/.torrt/config.json ...
INFO: Tracker `rutracker.org` is configured
```

**Comment by idlesign** [comment]
That's interesting. Unfortunatelly currently I have no access to rutracker to investigate the problem, so it'd probably take a while, before resolved.

**Comment by Vexxorian** [comment]
Torrent 4430338, qBittorrent RPC, worked on Python 3 with [quick fix filter](https://github.com/Vexxorian/torrt/commit/7372f35a4f4903b49d25cae1f1213baba3681bb3) being object now

    torrt add_torrent --verbose https://rutracker.org/forum/viewtopic.php?t=4430338
    
    DEBUG: Bootstrapping torrt environment ...
    DEBUG: Importing RPC classes ...
    DEBUG: Registering `deluge` from <class 'torrt.rpc.deluge.DelugeRPC'> ...
    DEBUG: Registering `qbittorrent` from <class 'torrt.rpc.qbittorrent.QBittorrentRPC'> ...
    DEBUG: Registering `transmission` from <class 'torrt.rpc.transmission.TransmissionRPC'> ...
    DEBUG: Registering `utorrent` from <class 'torrt.rpc.utorrent.UTorrentRPC'> ...
    DEBUG: Importing Tracker classes ...
    DEBUG: Registering `tr.anidub.com` from <class 'torrt.trackers.anidub.AniDUBTracker'> ...
    DEBUG: Registering `kinozal.tv` from <class 'torrt.trackers.kinozal.KinozalTracker'> ...
    DEBUG: Registering `nnm-club.me` from <class 'torrt.trackers.nnmclub.NNMClubTracker'> ...
    DEBUG: Registering `rutor.org` from <class 'torrt.trackers.rutor.RutorTracker'> ...
    DEBUG: Registering `rutracker.org` from <class 'torrt.trackers.rutracker.RuTrackerTracker'> ...
    DEBUG: Importing Notifier classes ...
    DEBUG: Registering `email` from <class 'torrt.notifiers.mail.EmailNotifier'> ...
    DEBUG: Registering `telegram` from <class 'torrt.notifiers.telegram.TelegramNotifier'> ...
    DEBUG: Initializing objects registries from configuration file ...
    DEBUG: Loading configuration file C:\Users\Vex\.torrt\config.json ...
    DEBUG: Spawning `QBittorrentRPC` object with the given settings ...
    DEBUG: Registering `qbittorrent` from <torrt.rpc.qbittorrent.QBittorrentRPC object at 0x00000000020D6208> ...
    DEBUG: Spawning `RuTrackerTracker` object with the given settings ...
    DEBUG: Registering `rutracker.org` from <torrt.trackers.rutracker.RuTrackerTracker object at 0x0000000003883A58> ...
    DEBUG: Adding torrent from `https://rutracker.org/forum/viewtopic.php?t=4430338` ...
    DEBUG: Downloading torrent file from `https://rutracker.org/forum/viewtopic.php?t=4430338` ...
    DEBUG: Picking a mirror ...
    DEBUG: Probing mirror: `https://rutracker.org` ...
    DEBUG: Starting new HTTPS connection (1): rutracker.org
    DEBUG: https://rutracker.org:443 "GET / HTTP/1.1" 301 178
    DEBUG: https://rutracker.org:443 "GET /forum/index.php HTTP/1.1" 200 None
    DEBUG: Fetching https://rutracker.org/forum/viewtopic.php?t=4430338 ...
    DEBUG: Starting new HTTPS connection (1): rutracker.org
    DEBUG: https://rutracker.org:443 "GET /forum/viewtopic.php?t=4430338 HTTP/1.1" 200 None
    DEBUG: Torrent download link found: https://rutracker.org/forum/dl.php?t=4430338
    DEBUG: Downloading torrent file from https://rutracker.org/forum/dl.php?t=4430338 ...
    DEBUG: Fetching https://rutracker.org/forum/dl.php?t=4430338 ...
    DEBUG: Starting new HTTPS connection (1): rutracker.org
    DEBUG: https://rutracker.org:443 "POST /forum/dl.php?t=4430338 HTTP/1.1" 200 39182
    DEBUG: Torrent was downloaded from `https://rutracker.org/forum/viewtopic.php?t=4430338`
    DEBUG: RPC action `login` ...
    DEBUG: Starting new HTTP connection (1): localhost
    DEBUG: http://localhost:8080 "POST /login HTTP/1.1" 200 3
    DEBUG: RPC action `add_torrent` ...
    DEBUG: Starting new HTTP connection (1): localhost
    DEBUG: http://localhost:8080 "POST /command/upload HTTP/1.1" 200 0
    DEBUG: Registering `17af70105c1fc4bf084a2a646a34319012379937` torrent ...
    DEBUG: Loading configuration file C:\Users\Vex\.torrt\config.json ...
    DEBUG: Saving configuration file C:\Users\Vex\.torrt\config.json ...
    INFO: Torrent from `https://rutracker.org/forum/viewtopic.php?t=4430338` is added within `qbittorrent`

**Comment by Bart39** [comment]
that still doesn't work for me (i was using python 2.7).
tried 3.5 and still did not work - same error

**Comment by idlesign** [comment]
It seems page dumps in debug mode should help us to investigate such problems (it is either our link regexp is broken or there's no such link on page as it seen by torrt).

I'll add sumping, but probably in a couple of weeks, when I return from vacation. But you can also try to do it yourself in base tracker class.

**Comment by Bart39** [comment]
ok, ive dumped the page as seen by torrt - [https://pastebin.com/ckT8w0aw](url)

edited down due to size but cut off where dl.php is
notice the weird spacing - thats why its not finding anything

**Comment by idlesign** [comment]
The right way of dumping would be composing html back from soup and dumping it. Is it the way you've done it?21:34, 13 апреля 2018 г., Bart39 <notifications@github.com>:ok, ive dumped the page as seen by torrt - https://pastebin.com/ckT8w0aw
edited down due to size but cut off where dl.php is
notice the weird spacing - thats why its not finding anything

**Comment by Vexxorian** [comment]
About dumping - [I tried](https://github.com/Vexxorian/torrt/commit/866bc38b7c1bbd9a78a3cf095013a4300a89ae2f), what do you think? [Example log](https://pastebin.com/mXjanBJc)  
The log made with `torrt ... > last.log 2>&1`. Not sure how to route this to file in a concise and configurable way without rewriting whole '[basic logging configuration](https://github.com/idlesign/torrt/blob/master/torrt/toolbox.py#L14)'

**Comment by idlesign** [comment]
@Bart39, I've made some improvements in `master`.

Unfortunately I have no access to rutracker, but you can dump pages (as they're seen by torrt) yourself with the help of `--dump` option.

This will dump pages scraped by torrt:
```
walk -f --dump .
```

After dumping you may want to archive produced html and share a link to it here, so we can help in investigation.

**Comment by idlesign** [comment]
Thank you @theonedemon , we'll bear in mind that old lxml might give us problems.

**Comment by cybcarr** [comment]
Hey there!

I don't know much about php, and stuff ( that is 0 ), but if your problem is as mine was in the past few weeks (0 peers for ages, and no starting torrents), my solution was protonvpn.com, and after a vuze magnet client did the trick, the qbittorrent still was useless. Hope it helped a bit. :)

**Comment by idlesign** [comment]
Considered closed. 
Feel free to reopen if required.
