### ISSUE TITLE
Bypass 451

### ISSUE THREAD

**Issue by ALTracer** [idlesign/torrt#22]
Neither rutracker nor telegram are directly accessible under all major ISPs in Russia. How do I connect torrt to these and `localhost` deluge api simultaneously?

Hint: often deluged+torrt+(?) bundle is often installed on a single dedicated node/home server, in my case, on a Raspberry Pi 3 running Raspbian Stretch. 

I have already set up tor+arm and configured deluged to communicate with trackers via `tor` socks proxy, and that works. As far as I can see, we need to route **https** sessions to rutracker and telegram through some https proxy (but `tor` itself does only `socks`). 

Tried `HTTPS_PROXY=https://user:pswd@example.com:443 torrt walk`, couldn't find a working proxy.

Tried torsocks torrt walk, and it wraps all outbound requests suitably for Tor but blocks `localhost` communication. Tried switching flags in `torsocks.conf` for Outbound and Inbound blocking, torrt (and other programs like curl, ping) errors out with 'DNS request failed'.

**Comment by idlesign** [comment]
Can't really advise you on how to access restricted resources.
Can only guess that some kind of special routing may be required specifically for them but not for localhost for example.

**Comment by ALTracer** [comment]
Looks like I denied localhost access in Tor's SocksPolicy "accept 192.168.1.0/24, reject *". Silly me.
Now I can configure and run this like `torsocks torrt walk` but now Telegram notifications are never sent. Log at [pastebin](https://pastebin.com/5kDQd2ep)

**Comment by idlesign** [comment]
Closing this. See `toolbox.tunnel()` for details.
