### ISSUE TITLE
Anilibria.tv changed rendering engine: AnilibriaTracker is no longer working

### ISSUE THREAD

**Issue by alexlitvinenko** [idlesign/torrt#29]
Anilibria has open-sourced [site code](https://github.com/anilibria/anilibria). We can try to use their [public API](https://github.com/anilibria/anilibria/blob/master/public/api/index.php) in order to rely on more stable links.

**Comment by idlesign** [comment]
Thank you for the report.

We could probably use API. Except it'd require more time to use it without docs (https://github.com/anilibria/anilibria/blob/master/private/api.php). Maybe it'll be easier to adopt new page layouts.

**Comment by idlesign** [comment]
Closed by #32.
