### ISSUE TITLE
anilibria.tv Cloudflare capture [RUS]

### ISSUE THREAD

**Issue by idlesign** [idlesign/torrt#46]
Тесты падают из-за показа страницы с капчей.
https://travis-ci.org/idlesign/torrt/jobs/584944270

Нужно что-то придумать. Если капча обходится наличием неких кук, то их нужно установить до первого запроса. Если не обойти, то встает вопрос либо о том, жизнеспособна ли поддержка этого трекера, либо о том, как модифицировать тесты, чтобы они могли ожидать падения конкретного трекера и сообщали о нём в отчёте, но не останавливали весь набор тестов.

**Comment by alexlitvinenko** [comment]
Не релевантно. Мы используем АПИ.

**Comment by idlesign** [comment]
Закрываю. Спасибо.
