### ISSUE TITLE
SSL InsecurePlatform error when using Requests package

### ISSUE THREAD

**Issue by dmzkrsk** [idlesign/torrt#5]
На старых версиях Python (у меня 2.7.6) при работе с HTTPS появляется warning:

```InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. For more information, see https://urllib3.readthedocs.org/en/latest/security.html#insecureplatformwarning```

На работу не влияет, но мешает

Решение есть тут: http://stackoverflow.com/questions/29099404/ssl-insecureplatform-error-when-using-requests-package

Мне помогла установка `pip install 'requests[security]'`, но я не знаю как это правильно записать в `setup.py`

**Comment by idlesign** [comment]
Спасибо за информацию.
В нашем случае лучше в качестве решения отключить эти предупреждения, только для старых версий питона.

**Comment by idlesign** [comment]
Оставляем на решение пользователям: пусть обновляются до версий ssl, считающихся безопасными на данный момент. Отдельно документировать не будем — проблема неспецифичная.

Спасибо за информацию.

**Comment by PatelAshish11** [comment]
https://icetutor.com/question/ssl-insecureplatform-error-when-using-requests-package/
