### ISSUE TITLE
 NNMClubTracker обновить зеркала [RUS]

### ISSUE THREAD

**Issue by theonedemon** [idlesign/torrt#52]
в файле trackers/nnmclub.py нужно заменить зеркала:
```
mirrors = ['nnm-club.name', 'nnmclub.to']
```
на 
```
mirrors = ['nnmclub.to', 'nnmclub.ro']
```
зеркало nnm-club.nameуже не рабочее и при получении торрента висим 30 секунд ( по таймауту )

**Comment by idlesign** [comment]
Спасибо. Сделаем, как руки дойдут.

**Comment by idlesign** [comment]
Дошли руки, подновил.
Спасибо.
