### ISSUE TITLE
[yts.mx] tests failing because test URL was pulled by DCMA (?)

### ISSUE THREAD

**Issue by NecroKote** [idlesign/torrt#79]
From one of the latest runs of `coveralls`:
```
RROR    torrt:utils.py:585 YtsmxTracker: div#movie-info not found on page
ERROR    torrt:utils.py:585 YtsmxTracker: Cannot find torrent file download link at https://yts.mx/movies/the-matrix-resurrections-2021
WARNING  torrt:utils.py:458 Unable to get torrent from `https://yts.mx/movies/the-matrix-resurrections-2021`
```
(source #78)

Seems like someone just pulled plug on latest Matrix at yts.mx ...

As a fix we *can* replace test-url for that tracker by some other URL, for example: `https://yts.mx/movies/the-matrix-1999`

But that made me thinking... Maybe testing tracker's ability to parse pages during auto-test process is not the wisest idea ? 
Maybe it's better we mark all other tracker's tests with pytest mark `tracker` (or any other alternative) and don't run it during regular building process but allow users to test for *tracker fittness* themselves ?

**Comment by idlesign** [comment]
In this case we'd rather stick to quiering real pages since it slightly increases chances to spot failures sooner.

To address the issue: the best test url would be that with some opensource, or an old but popular title which became a public domain.
