### ISSUE TITLE
Errors with python-telegram-bot 12 [RUS]

### ISSUE THREAD

**Issue by Askaniy** [idlesign/torrt#83]
Добрый вечер! Следуя документации, попробовал создать Телеграм-бота, но неуспешно. После `torrt run_bots` был выдан ряд предупреждений `TelegramDeprecationWarning` со ссылкой на [документацию перехода на 12 версию](https://github.com/python-telegram-bot/python-telegram-bot/wiki/Transition-guide-to-Version-12.0). Ответить на сообщение `/start` бот уже не смог:
```py
File "/home/askaniy/.local/lib/python3.10/site-packages/torrt/bots/telegram_bot.py", line 241, in command_start
    bot.send_message(update.message.chat_id, 'What do you want to do?', reply_markup=kb)
AttributeError: 'Update' object has no attribute 'send_message'
```
На Питоне программировать умею (не ботов) и наверное мог бы исправить (помучавшись), но лучше подожду исправления от автора. И да, вам не сложно привести образец использования интерфейса Питона? Документации не хватает.

**Comment by idlesign** [comment]
Доброго дня,

Я правильно понимаю, что установлена версия из PyPI?
Если так, попробуйте установить прямо из master: `pip install git+https://github.com/idlesign/torrt.git`
Там был переход на новую версию: `python-telegram-bot >=13.10, <14.0.0a0` #75

**Comment by Askaniy** [comment]
Переустановил, теперь работает, спасибо.
