### ISSUE TITLE
Как работает автоматизация проверки торрентов?

### ISSUE THREAD

**Issue by ananasjk** [idlesign/torrt#88]
В документации нет чёткого ответа, поэтому решил что лучше спросить. "Automatically checks" means? Как настроить именно автоматическую проверку, чтобы раз в условно 12 часов проводился чек по списку?

**Comment by idlesign** [comment]
Торрт пройдёт по списку и обновит торренты автоматически тогда, когда вы скажете ему это сделать.
Вызов команды `torrt walk` как раз этим занимается. 

Если вы зададите расписание, например, в `cron`, чтобы эта команда запускалась через определённый промежуток времени, то она будет запускаться: 
```
0 */12 * * * torrt walk
```


Или, если вы пропишите запуск команды при начале сеанса вашей операционной системы, она тоже выполнится.

**Comment by ananasjk** [comment]
Понял, спасибо большое! Возможно стоит добавить это в документацию, чтобы у таких же чайников как я не возникало подобных вопросов?

**Comment by idlesign** [comment]
> Понял, спасибо большое! Возможно стоит добавить это в документацию, чтобы у таких же чайников как я не возникало подобных вопросов?

Пожалуйста. Если у вас есть силы и возможность как-то улучшить документацию или код, то я буду рад рассмотреть запрос на вливание кода.
