### ISSUE TITLE
Rutracker login fails [rus]

### ISSUE THREAD

**Issue by ALTracer** [idlesign/torrt#9]
Во-первых, страница логина более не login.rutr..., а rutr... #8 
Во-вторых, всё равно не могу авторизоваться, потому что мой ник состоит из двух слов на русском, разделённых пробелом.

**Comment by idlesign** [comment]
Сейчас рутрекером не пользуюсь, проверить не смогу. 
Вероятно нужно кодировать подобные логины. Если сможете решить, приму в версию.

**Comment by ALTracer** [comment]
Открыл страницу логина в браузере на том же Raspberry Pi 3, где крутится Deluge (хотя всё равно домашняя сеть за роутером)
Сайт просит ввести цифры с капчи. Возможно, связано с этим. Всё равно нет DNS-записей для 'login.rutr..'

**Comment by idlesign** [comment]
Капча показывается после неудачной попытки авторизации.
Можно авторизоваться вручную, можно подождать пока сессия в форуме протухнет.

**Comment by ALTracer** [comment]
Подождал. Нет.
https://pastebin.com/PpmGhtGa

**Comment by boganov** [comment]
Такая же проблема. Не удалось найти решение?

**Comment by idlesign** [comment]
Я не искал, давно не был на рутрекере. Займусь, если найду время.

**Comment by boganov** [comment]
Не очень разбираюсь в питоне и вообще в том как устроены ответы от рутрекера, но там в base_tracker.py есть строчка 397, где проверяются какие-то условия ответа от сервера. Вот есть не проверять (написать что-то типа if True:), то все работает, но скорее всего, образуется большая дыра. Оставил так, пока все ок! И спасибо за программу, давно искал что-то такое!

**Comment by idlesign** [comment]
Пожалуйста. 
Будет время — гляну.

**Comment by JumperAlexey** [comment]
Автор, спасибо за проделанную работу. Можно с вами как то связаться и задать пару вопросов по установке? Или как тут принято обращатся с вопросами? Я тут новенький, прошу сильно не пинать.

**Comment by idlesign** [comment]
@JumperAlexey Пожалуйста.
Установка описана здесь: https://github.com/idlesign/torrt/blob/master/INSTALL
А настройка описана здесь: http://torrt.readthedocs.io/en/latest/quickstart.html

Если есть, какие-то другие вопросы, то можно создать задачу - https://github.com/idlesign/torrt/issues/new (в конце названия не забудьте поставить пометку [rus], если планируете писать на русском).

**Comment by JumperAlexey** [comment]
Спасибо за оперативный ответ. Завтра максимально подробно опишу вопрос в новой задаче. Инструкции и гугл читал и все делал как написано.

**Comment by idlesign** [comment]
По всей видимости, решено в 0.7.1.
